### PR TITLE
Ensure backend is initialized on import

### PR DESCRIPTION
**Pull request by philippjfr**
- [x] Fixes https://github.com/pyviz/geoviews/issues/273

### CODE REVIEW

**Comment by TimoRoth** [comment]
I'm getting errors after upgrading to 1.6.1 due to this:

```
Traceback (most recent call last):
  File "./app.py", line 18, in <module>
    import geoviews as gv
  File "/home/users/timo/oggm_venv/lib/python3.7/site-packages/geoviews/__init__.py", line 30, in <module>
    if extension._loaded:
AttributeError: type object 'extension' has no attribute '_loaded'
```

frozen environment: https://bpaste.net/show/70053f841805

**Comment by philippjfr** [comment]
@TimoRoth You will have to upgrade holoviews to a minimum of 1.11.0 and pyviz_comms to a minimum of 0.7.0.

**Comment by philippjfr** [comment]
Hmm, your environment seems to indicate you have those versions. Not quite sure how this could happen with those versions but I'll have a look.

**Comment by philippjfr** [comment]
Okay nevermind, I can see how it can happen. I'll push a fix shortly and then tag 1.6.2.
